FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y \
        wine64 \
        wine32 \
        winbind \
        cabextract \
        curl \
        iproute2 \
        iputils-ping \
        net-tools \
        procps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

CMD ["sleep", "infinity"]