#version: "3.9"

networks:
  testnet:
    driver: bridge

services:
  server:
    image: nginx
    networks:
      - testnet
  #  ports:
  #    - "8080:80"

  client1:
    image: curlimages/curl
    command: sleep infinity
    networks:
      - testnet

  client2:
    image: curlimages/curl
    command: sleep infinity
    networks:
      - testnet

  client3:
    image: curlimages/curl
    command: sleep infinity
    networks:
      - testnet
      
  attacker:
    image: nicolaka/netshoot
    command: sleep infinity
    networks:
      - testnet

  sensor:
    image: nicolaka/netshoot
    networks:
      - testnet
    command: sh -c "tcpdump -i eth0 -nn -s 0 -w /pcaps/capture.pcap"
    volumes:
      - ./pcaps:/pcaps